name: Lint and Test

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
          python-version: 3.12
    - name: Install test dependencies
      run: |
        python -m pip install --upgrade pip
        pip install uv
        uv sync requirements-test.txt
    - name: Test with pytest
      run: |
        pytest .
    - name: Install linting dependencies
      run: |
        uv sync requirements-dev.txt
    - name: Lint
      run: |
        pre-commit run -a
