name: Lint and Test

on:
  pull_request:
  push:
    branches: [main]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
          python-version: 3.12
    - name: Install test dependencies
      run: |
        python -m pip install --upgrade pip
        pip install uv
        uv venv --python=3.12 .venv
        source .venv/bin/activate
        uv pip sync requirements-test.txt
    - name: Test with pytest
      run: |
        .venv/bin/pytest .
    - name: Install linting dependencies
      run: |
        source .venv/bin/activate
        uv pip install -r requirements-dev.txt
        # in order to have all types available for type checker
        uv pip install -r web/requirements.txt
    - name: Lint
      run: |
        .venv/bin/pre-commit run -a
